"""Add onboarding_complete column to users table

Revision ID: 74944963cbb1
Revises: 
Create Date: 2025-09-13 23:11:58.505848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74944963cbb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_complete')

    # ### end Alembic commands ###
