"""Add place_id field to hotels table

Revision ID: add_place_id_hotels
Revises: 74944963cbb1
Create Date: 2025-09-14 12:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_place_id_hotels'
down_revision = '74944963cbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_hotels_place_id'), ['place_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_place_id'))
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
